unit SearchForm;

interface

uses
  Forms, StdCtrls, Controls, Spin, ComCtrls, Classes, Windows;

type
  TfrmSearch = class(TForm)
    pcSearchOptions: TPageControl;
    tsGeneral: TTabSheet;
    gbGeneral: TGroupBox;
    lblName: TLabel;
    lblAge: TLabel;
    lblNation: TLabel;
    lblDivision: TLabel;
    lblBased: TLabel;
    lblAgeLine: TLabel;
    edName: TEdit;
    cbEUNational: TCheckBox;
    speMinAge: TSpinEdit;
    cmbNation: TComboBox;
    cmbBased: TComboBox;
    cmbDivision: TComboBox;
    speMaxAge: TSpinEdit;
    gbPositions: TGroupBox;
    cbGoalkeeper: TCheckBox;
    cbDefender: TCheckBox;
    cbDefensiveMidfielder: TCheckBox;
    cbMidfielder: TCheckBox;
    cbAttackingMidfielder: TCheckBox;
    cbAttacker: TCheckBox;
    cbSweeper: TCheckBox;
    cbLeftSide: TCheckBox;
    cbFreeRole: TCheckBox;
    cbCentral: TCheckBox;
    cbRightSide: TCheckBox;
    cbWingBack: TCheckBox;
    gbAbility: TGroupBox;
    lblAbility: TLabel;
    lblPotentialAbility: TLabel;
    lblScoutRating: TLabel;
    lblAbilityLine: TLabel;
    lblPotentialAbilityLine: TLabel;
    lblScoutRatingLine: TLabel;
    speAbilityMin: TSpinEdit;
    spePotentialAbilityMin: TSpinEdit;
    speScoutRatingMin: TSpinEdit;
    speAbilityMax: TSpinEdit;
    spePotentialAbilityMax: TSpinEdit;
    speScoutRatingMax: TSpinEdit;
    gbReputation: TGroupBox;
    lblHomeReputation: TLabel;
    lblHomeReputationLine: TLabel;
    lblCurrentReputation: TLabel;
    lblCurrentReputationLine: TLabel;
    lblWorldReputation: TLabel;
    lblWorldReputationLine: TLabel;
    lblSquadReputation: TLabel;
    lblSquadReputationLine: TLabel;
    speHomeReputationMin: TSpinEdit;
    speHomeReputationMax: TSpinEdit;
    speCurrentReputationMin: TSpinEdit;
    speCurrentReputationMax: TSpinEdit;
    speWorldReputationMin: TSpinEdit;
    speWorldReputationMax: TSpinEdit;
    speSquadReputationMin: TSpinEdit;
    speSquadReputationMax: TSpinEdit;
    FtsContract: TTabSheet;
    gbContract: TGroupBox;
    lblContract: TLabel;
    cmbContract: TComboBox;
    cbLeavingOnBosman: TCheckBox;
    gbStatus: TGroupBox;
    lblTransferStatus: TLabel;
    lblSquadStatus: TLabel;
    cmbTransferStatus: TComboBox;
    cmbSquadStatus: TComboBox;
    gbReleaseClauses: TGroupBox;
    lblReleaseFee: TLabel;
    lblReleaseFeeLine: TLabel;
    cbNonPromotion: TCheckBox;
    cbNonPromotionActive: TCheckBox;
    cbRelegation: TCheckBox;
    cbRelegationActive: TCheckBox;
    cbMinimumFee: TCheckBox;
    speMinReleaseFee: TSpinEdit;
    speMaxReleaseFee: TSpinEdit;
    gbContractDetails: TGroupBox;
    lblContractType: TLabel;
    lblValue: TLabel;
    lblWage: TLabel;
    lblValueLine: TLabel;
    lblWageLine: TLabel;
    cmbContractType: TComboBox;
    speMinValue: TSpinEdit;
    speMaxValue: TSpinEdit;
    speMinWage: TSpinEdit;
    speMaxWage: TSpinEdit;
    FtsAttributes1: TTabSheet;
    FtsAttributes2: TTabSheet;
    btnOK: TButton;
    btnCancel: TButton;
    btnReset: TButton;
    lblSaleValue: TLabel;
    lblSaleValueLine: TLabel;
    speMinSaleValue: TSpinEdit;
    speMaxSaleValue: TSpinEdit;
    lblCaps: TLabel;
    lblCapsLine: TLabel;
    speMinCaps: TSpinEdit;
    speMaxCaps: TSpinEdit;
    lblIntGoals: TLabel;
    lblIntGoalsLine: TLabel;
    speMinIntGoals: TSpinEdit;
    speMaxIntGoals: TSpinEdit;
    FtsAttributes3: TTabSheet;
    lblAcceleration: TLabel;
    lblAccelerationLine: TLabel;
    speMinAcceleration: TSpinEdit;
    speMaxAcceleration: TSpinEdit;
    lblAdaptability: TLabel;
    lblAdaptabilityLine: TLabel;
    speMinAdaptability: TSpinEdit;
    speMaxAdaptability: TSpinEdit;
    lblAerialAbility: TLabel;
    lblAerialAbilityLine: TLabel;
    speMinAerialAbility: TSpinEdit;
    speMaxAerialAbility: TSpinEdit;
    lblAggression: TLabel;
    lblAggressionLine: TLabel;
    speMinAggression: TSpinEdit;
    speMaxAggression: TSpinEdit;
    lblAgility: TLabel;
    lblAgilityLine: TLabel;
    speMinAgility: TSpinEdit;
    speMaxAgility: TSpinEdit;
    lblAmbition: TLabel;
    lblAmbitionLine: TLabel;
    speMinAmbition: TSpinEdit;
    speMaxAmbition: TSpinEdit;
    lblAnticipation: TLabel;
    lblAnticipationLine: TLabel;
    speMinAnticipation: TSpinEdit;
    speMaxAnticipation: TSpinEdit;
    lblBalance: TLabel;
    lblBalanceLine: TLabel;
    speMinBalance: TSpinEdit;
    speMaxBalance: TSpinEdit;
    lblBravery: TLabel;
    lblBraveryLine: TLabel;
    speMinBravery: TSpinEdit;
    speMaxBravery: TSpinEdit;
    lblCommandOfArea: TLabel;
    lblCommandOfAreaLine: TLabel;
    speMinCommandOfArea: TSpinEdit;
    speMaxCommandOfArea: TSpinEdit;
    lblCommunication: TLabel;
    lblCommunicationLine: TLabel;
    speMinCommunication: TSpinEdit;
    speMaxCommunication: TSpinEdit;
    lblConsistency: TLabel;
    lblConsistencyLine: TLabel;
    speMinConsistency: TSpinEdit;
    speMaxConsistency: TSpinEdit;
    lblControversy: TLabel;
    lblControversyLine: TLabel;
    speMinControversy: TSpinEdit;
    speMaxControversy: TSpinEdit;
    lblCorners: TLabel;
    lblCornersLine: TLabel;
    speMinCorners: TSpinEdit;
    speMaxCorners: TSpinEdit;
    lblCreativity: TLabel;
    lblCreativityLine: TLabel;
    speMinCreativity: TSpinEdit;
    speMaxCreativity: TSpinEdit;
    lblCrossing: TLabel;
    lblCrossingLine: TLabel;
    speMinCrossing: TSpinEdit;
    speMaxCrossing: TSpinEdit;
    lblDecisions: TLabel;
    lblDecisionsLine: TLabel;
    speMinDecisions: TSpinEdit;
    speMaxDecisions: TSpinEdit;
    lblDetermination: TLabel;
    lblDeterminationLine: TLabel;
    speMinDetermination: TSpinEdit;
    speMaxDetermination: TSpinEdit;
    lblDirtiness: TLabel;
    lblDirtinessLine: TLabel;
    speMinDirtiness: TSpinEdit;
    speMaxDirtiness: TSpinEdit;
    lblDribbling: TLabel;
    lblDribblingLine: TLabel;
    speMinDribbling: TSpinEdit;
    speMaxDribbling: TSpinEdit;
    lblImportantMatches: TLabel;
    lblImportantMatchesLine: TLabel;
    speMinImportantMatches: TSpinEdit;
    speMaxImportantMatches: TSpinEdit;
    lblInfluence: TLabel;
    lblInfluenceLine: TLabel;
    speMinInfluence: TSpinEdit;
    speMaxInfluence: TSpinEdit;
    lblInjuryProneness: TLabel;
    lblInjuryPronenessLine: TLabel;
    speMinInjuryProneness: TSpinEdit;
    speMaxInjuryProneness: TSpinEdit;
    lblJumping: TLabel;
    lblJumpingLine: TLabel;
    speMinJumping: TSpinEdit;
    speMaxJumping: TSpinEdit;
    lblKicking: TLabel;
    lblKickingLine: TLabel;
    speMinKicking: TSpinEdit;
    speMaxKicking: TSpinEdit;
    lblLeftFoot: TLabel;
    lblLeftFootLine: TLabel;
    speMinLeftFoot: TSpinEdit;
    speMaxLeftFoot: TSpinEdit;
    lblLongShots: TLabel;
    lblLongShotsLine: TLabel;
    speMinLongShots: TSpinEdit;
    speMaxLongShots: TSpinEdit;
    lblLongThrows: TLabel;
    lblLongThrowsLine: TLabel;
    speMinLongThrows: TSpinEdit;
    speMaxLongThrows: TSpinEdit;
    lblLoyality: TLabel;
    lblLoyalityLine: TLabel;
    speMinLoyality: TSpinEdit;
    speMaxLoyality: TSpinEdit;
    lblMarking: TLabel;
    lblMarkingLine: TLabel;
    speMinMarking: TSpinEdit;
    speMaxMarking: TSpinEdit;
    lblNaturalFitness: TLabel;
    lblNaturalFitnessLine: TLabel;
    speMinNaturalFitness: TSpinEdit;
    speMaxNaturalFitness: TSpinEdit;
    lblOffTheBall: TLabel;
    lblOffTheBallLine: TLabel;
    speMinOffTheBall: TSpinEdit;
    speMaxOffTheBall: TSpinEdit;
    lblOneOnOnes: TLabel;
    lblOneOnOnesLine: TLabel;
    speMinOneOnOnes: TSpinEdit;
    speMaxOneOnOnes: TSpinEdit;
    lblPace: TLabel;
    lblPaceLine: TLabel;
    speMinPace: TSpinEdit;
    speMaxPace: TSpinEdit;
    lblFlair: TLabel;
    lblFlairLine: TLabel;
    speMinFlair: TSpinEdit;
    speMaxFlair: TSpinEdit;
    lblHandling: TLabel;
    lblHandlingLine: TLabel;
    speMinHandling: TSpinEdit;
    speMaxHandling: TSpinEdit;
    lblHeading: TLabel;
    lblHeadingLine: TLabel;
    speMinHeading: TSpinEdit;
    speMaxHeading: TSpinEdit;
    lblEccentricity: TLabel;
    lblEccentricityLine: TLabel;
    speMinEccentricity: TSpinEdit;
    speMaxEccentricity: TSpinEdit;
    lblFinishing: TLabel;
    lblFinishingLine: TLabel;
    speMinFinishing: TSpinEdit;
    speMaxFinishing: TSpinEdit;
    lblFirstTouch: TLabel;
    lblFirstTouchLine: TLabel;
    speMinFirstTouch: TSpinEdit;
    speMaxFirstTouch: TSpinEdit;
    lblTackling: TLabel;
    lblTacklingLine: TLabel;
    speMinTackling: TSpinEdit;
    speMaxTackling: TSpinEdit;
    lblTeamwork: TLabel;
    lblTeamworkLine: TLabel;
    speMinTeamwork: TSpinEdit;
    speMaxTeamwork: TSpinEdit;
    lblTechnique: TLabel;
    lblTechniqueLine: TLabel;
    speMinTechnique: TSpinEdit;
    speMaxTechnique: TSpinEdit;
    lblTemperament: TLabel;
    lblTemperamentLine: TLabel;
    speMinTemperament: TSpinEdit;
    speMaxTemperament: TSpinEdit;
    lblTendencyToPunch: TLabel;
    lblTendencyToPunchLine: TLabel;
    speMinTendencyToPunch: TSpinEdit;
    speMaxTendencyToPunch: TSpinEdit;
    lblThrowing: TLabel;
    lblThrowingLine: TLabel;
    speMinThrowing: TSpinEdit;
    speMaxThrowing: TSpinEdit;
    lblThrowIns: TLabel;
    lblThrowInsLine: TLabel;
    speMinThrowIns: TSpinEdit;
    speMaxThrowIns: TSpinEdit;
    lblVersatility: TLabel;
    lblVersatilityLine: TLabel;
    speMinVersatility: TSpinEdit;
    speMaxVersatility: TSpinEdit;
    lblWorkRate: TLabel;
    lblWorkRateLine: TLabel;
    speMinWorkRate: TSpinEdit;
    speMaxWorkRate: TSpinEdit;
    lblStamina: TLabel;
    lblStaminaLine: TLabel;
    speMinStamina: TSpinEdit;
    speMaxStamina: TSpinEdit;
    lblStrength: TLabel;
    lblStrengthLine: TLabel;
    speMinStrength: TSpinEdit;
    speMaxStrength: TSpinEdit;
    lblPassing: TLabel;
    lblPassingLine: TLabel;
    speMinPassing: TSpinEdit;
    speMaxPassing: TSpinEdit;
    lblPenalties: TLabel;
    lblPenaltiesLine: TLabel;
    speMinPenalties: TSpinEdit;
    speMaxPenalties: TSpinEdit;
    lblPositioning: TLabel;
    lblPositioningLine: TLabel;
    speMinPositioning: TSpinEdit;
    speMaxPositioning: TSpinEdit;
    lblPressure: TLabel;
    lblPressureLine: TLabel;
    speMinPressure: TSpinEdit;
    speMaxPressure: TSpinEdit;
    lblProfessionalism: TLabel;
    lblProfessionalismLine: TLabel;
    speMinProfessionalism: TSpinEdit;
    speMaxProfessionalism: TSpinEdit;
    lblReflexes: TLabel;
    lblReflexesLine: TLabel;
    speMinReflexes: TSpinEdit;
    speMaxReflexes: TSpinEdit;
    lblRightFoot: TLabel;
    lblRightFootLine: TLabel;
    speMinRightFoot: TSpinEdit;
    speMaxRightFoot: TSpinEdit;
    lblRushingOut: TLabel;
    lblRushingOutLine: TLabel;
    speMinRushingOut: TSpinEdit;
    speMaxRushingOut: TSpinEdit;
    lblSetPieces: TLabel;
    lblSetPiecesLine: TLabel;
    speMinSetPieces: TSpinEdit;
    speMaxSetPieces: TSpinEdit;
    lblSportsmanship: TLabel;
    lblSportsmanshipLine: TLabel;
    speMinSportsmanship: TSpinEdit;
    speMaxSportsmanship: TSpinEdit;
    procedure speKeyDown(Sender: TObject; var Key: Word;
      Shift: TShiftState);
    procedure btnResetClick(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

implementation

{$R *.dfm}

procedure TfrmSearch.speKeyDown(Sender: TObject; var Key: Word;
  Shift: TShiftState);
begin
  if (Ord(Key) = VK_RETURN) then
    btnOK.Click;
  if (Ord(Key) = VK_ESCAPE) then
    btnCancel.Click;
end;

procedure TfrmSearch.btnResetClick(Sender: TObject);
begin
  edName.Text:='';
  speMinAge.Value:=0;
  speMaxAge.Value:=0;
  cmbNation.ItemIndex:=-1;
  cbEUNational.Checked:=False;
  speMinCaps.Value:=0;
  speMaxCaps.Value:=0;
  speMinIntGoals.Value:=0;
  speMaxIntGoals.Value:=0;
  cmbBased.ItemIndex:=-1;
  cmbDivision.ItemIndex:=-1;
  cbGoalkeeper.Checked:=False;
  cbDefender.Checked:=False;
  cbMidfielder.Checked:=False;
  cbAttacker.Checked:=False;
  cbSweeper.Checked:=False;
  cbDefensiveMidfielder.Checked:=False;
  cbAttackingMidfielder.Checked:=False;
  cbLeftSide.Checked:=False;
  cbRightSide.Checked:=False;
  cbCentral.Checked:=False;
  cbWingBack.Checked:=False;
  cbFreeRole.Checked:=False;
  speAbilityMin.Value:=0;
  speAbilityMax.Value:=200;
  spePotentialAbilityMin.Value:=0;
  spePotentialAbilityMax.Value:=200;
  speScoutRatingMin.Value:=0;
  speScoutRatingMax.Value:=100;
  speHomeReputationMin.Value:=0;
  speHomeReputationMax.Value:=10000;
  speCurrentReputationMin.Value:=0;
  speCurrentReputationMax.Value:=10000;
  speWorldReputationMin.Value:=0;
  speWorldReputationMax.Value:=10000;
  speSquadReputationMin.Value:=0;
  speSquadReputationMax.Value:=10000;
  cmbContract.ItemIndex:=-1;
  cbLeavingOnBosman.Checked:=False;
  cbNonPromotion.Checked:=False;
  cbNonPromotionActive.Checked:=False;
  cbRelegation.Checked:=False;
  cbRelegationActive.Checked:=False;
  cbMinimumFee.Checked:=False;
  speMinReleaseFee.Value:=0;
  speMaxReleaseFee.Value:=0;
  cmbTransferStatus.ItemIndex:=-1;
  cmbSquadStatus.ItemIndex:=-1;
  cmbContractType.ItemIndex:=-1;
  speMinValue.Value:=0;
  speMaxValue.Value:=0;
  speMinSaleValue.Value:=0;
  speMaxSaleValue.Value:=0;
  speMinWage.Value:=0;
  speMaxWage.Value:=0;
  speMinAcceleration.Value:=0;
  speMaxAcceleration.Value:=20;
  speMinAdaptability.Value:=0;
  speMaxAdaptability.Value:=20;
  speMinAerialAbility.Value:=0;
  speMaxAerialAbility.Value:=20;
  speMinAggression.Value:=0;
  speMaxAggression.Value:=20;
  speMinAgility.Value:=0;
  speMaxAgility.Value:=20;
  speMinAmbition.Value:=0;
  speMaxAmbition.Value:=20;
  speMinAnticipation.Value:=0;
  speMaxAnticipation.Value:=20;
  speMinBalance.Value:=0;
  speMaxBalance.Value:=20;
  speMinBravery.Value:=0;
  speMaxBravery.Value:=20;
  speMinCommandOfArea.Value:=0;
  speMaxCommandOfArea.Value:=20;
  speMinCommunication.Value:=0;
  speMaxCommunication.Value:=20;
  speMinConsistency.Value:=0;
  speMaxConsistency.Value:=20;
  speMinControversy.Value:=0;
  speMaxControversy.Value:=20;
  speMinCorners.Value:=0;
  speMaxCorners.Value:=20;
  speMinCreativity.Value:=0;
  speMaxCreativity.Value:=20;
  speMinCrossing.Value:=0;
  speMaxCrossing.Value:=20;
  speMinDecisions.Value:=0;
  speMaxDecisions.Value:=20;
  speMinDetermination.Value:=0;
  speMaxDetermination.Value:=20;
  speMinDirtiness.Value:=0;
  speMaxDirtiness.Value:=20;
  speMinDribbling.Value:=0;
  speMaxDribbling.Value:=20;
  speMinEccentricity.Value:=0;
  speMaxEccentricity.Value:=20;
  speMinFinishing.Value:=0;
  speMaxFinishing.Value:=20;
  speMinFirstTouch.Value:=0;
  speMaxFirstTouch.Value:=20;
  speMinFlair.Value:=0;
  speMaxFlair.Value:=20;
  speMinHandling.Value:=0;
  speMaxHandling.Value:=20;
  speMinHeading.Value:=0;
  speMaxHeading.Value:=20;
  speMinImportantMatches.Value:=0;
  speMaxImportantMatches.Value:=20;
  speMinInfluence.Value:=0;
  speMaxInfluence.Value:=20;
  speMinInjuryProneness.Value:=0;
  speMaxInjuryProneness.Value:=20;
  speMinJumping.Value:=0;
  speMaxJumping.Value:=20;
  speMinKicking.Value:=0;
  speMaxKicking.Value:=20;
  speMinLeftFoot.Value:=0;
  speMaxLeftFoot.Value:=20;
  speMinLongShots.Value:=0;
  speMaxLongShots.Value:=20;
  speMinLongThrows.Value:=0;
  speMaxLongThrows.Value:=20;
  speMinLoyality.Value:=0;
  speMaxLoyality.Value:=20;
  speMinMarking.Value:=0;
  speMaxMarking.Value:=20;
  speMinNaturalFitness.Value:=0;
  speMaxNaturalFitness.Value:=20;
  speMinOffTheBall.Value:=0;
  speMaxOffTheBall.Value:=20;
  speMinOneOnOnes.Value:=0;
  speMaxOneOnOnes.Value:=20;
  speMinPace.Value:=0;
  speMaxPace.Value:=20;
  speMinPassing.Value:=0;
  speMaxPassing.Value:=20;
  speMinPenalties.Value:=0;
  speMaxPenalties.Value:=20;
  speMinPositioning.Value:=0;
  speMaxPositioning.Value:=20;
  speMinPressure.Value:=0;
  speMaxPressure.Value:=20;
  speMinProfessionalism.Value:=0;
  speMaxProfessionalism.Value:=20;
  speMinReflexes.Value:=0;
  speMaxReflexes.Value:=20;
  speMinRightFoot.Value:=0;
  speMaxRightFoot.Value:=20;
  speMinRushingOut.Value:=0;
  speMaxRushingOut.Value:=20;
  speMinSetPieces.Value:=0;
  speMaxSetPieces.Value:=20;
  speMinSportsmanship.Value:=0;
  speMaxSportsmanship.Value:=20;
  speMinStamina.Value:=0;
  speMaxStamina.Value:=20;
  speMinStrength.Value:=0;
  speMaxStrength.Value:=20;
  speMinTackling.Value:=0;
  speMaxTackling.Value:=20;
  speMinTeamwork.Value:=0;
  speMaxTeamwork.Value:=20;
  speMinTechnique.Value:=0;
  speMaxTechnique.Value:=20;
  speMinTemperament.Value:=0;
  speMaxTemperament.Value:=20;
  speMinTendencyToPunch.Value:=0;
  speMaxTendencyToPunch.Value:=20;
  speMinThrowing.Value:=0;
  speMaxThrowing.Value:=20;
  speMinThrowIns.Value:=0;
  speMaxThrowIns.Value:=20;
  speMinVersatility.Value:=0;
  speMaxVersatility.Value:=20;
  speMinWorkRate.Value:=0;
  speMaxWorkRate.Value:=20;
end;

end.
